{
 "title": "Overview [Fahrenheit]",
 "description": "Weather dashboard with units in °F",
 "tags": [
  "weather",
  "demo"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   {
    "name": "location",
    "label": "Location",
    "query": "label_values(weather_temp_c, location)"
   },
   { "name": "forecast_day", "label": "Forecast Days", "query": "label_values(forecast_day)" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg(weather_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feels Like Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg(weather_feelslike_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg(weather_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location) * 1.8 + 32",
     "legendFormat": "Actual Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_feelslike_temp_c{job=\"weather-service\",location=~\"$location\"}) by (location) * 1.8 + 32",
     "legendFormat": "Perceived Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location) * 1.8 + 32",
     "legendFormat": "Predicted Temperature - {{ location }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(weather_humidity{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(weather_humidity{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "Actual Humidity - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_humidity{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location)",
     "legendFormat": "Predicted Humidity - {{ location }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<div>\n  <a href=\"/connections/add-new-connection/?src=click_top_cta_connect_data_weather\" target=\"_blank\"/>\n    <h1 style=\"\n        background: linear-gradient(120deg, rgb(30,144,255), rgb(30,144,255));\n        text-align: center;\n        font-size: 1.5em;\n        padding: 0.3em;\n        color: black;\n    \">\n      + Connect my data\n    </h1>\n  </a>\n</div>\n"
   }
  },
  {
   "type": "geomap",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg(weather_location_info{job=\"weather-service\", location=~\"$location\"}) by (location,lat,lon)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(weather_uv_index{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(weather_uv_index{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "Actual UV Index - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_uv_index{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "Predicted UV Index - {{ location }}"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "avg(weather_wind_speed{job=\"weather-service\",location=~\"$location\"}) by (location) * 0.6213711922",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"weather-service\"} |= \"wind_dir\" |~ \"$location\" | logfmt"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "avg(weather_wind_speed{job=\"weather-service\",location=~\"$location\"}) by (location) * 0.6213711922",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "expr": "avg(weather_precip_mm{job=\"weather-service\",location=~\"$location\"}) by (location)* 0.03937007874",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "options": {
    "content": "---\n### **Connect your own data**\n\nUsing the Grafana Cloud Infinity Plugin, you can import and visualize data from JSON, CSV, XML, GraphQL, and HTML endpoints. \n\nClick the **+ Connect my data** button below to get started!\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 23 },
   "options": {
    "content": "<div>\n  <a href=\"/connections/datasources/yesoreyeram-infinity-datasource/?src=click_second_cta_connect_data_weather\" target=\"_blank\"/>\n    <h1 style=\"\n        background: linear-gradient(120deg, rgb(30,144,255), rgb(30,144,255));\n        text-align: center;\n        font-size: 1.5em;\n        padding: 0.3em;\n        color: black;\n    \">\n      + Connect my data\n    </h1>\n  </a>\n</div>\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 14, "y": 25 }, "options": { "content": "---" } },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(weather_precip_mm{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "Actual Precipitation - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_precip_mm{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location)",
     "legendFormat": "Predicted Precipitation - {{ location }}"
    }
   ]
  },
  {
   "title": "Condition",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{namespace=\"weather-service\"} |= \"Current Condition\" | logfmt | location=~\"$location\""
    }
   ]
  },
  {
   "title": "Forecast for today + $forecast_day days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "forecast_day"
  },
  {
   "title": "Forecast Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forecast Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location) * 1.8 + 32",
     "legendFormat": "Forecast Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_max_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location) * 1.8 + 32",
     "legendFormat": "Forecast Max Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_min_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location) * 1.8 + 32",
     "legendFormat": "Forecast Min Temperature - {{ location }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 36 },
   "options": {
    "content": "### **Create an Alert for Temperature**\n\nUsing the Grafana Cloud Alerting, you can set up alerts to monitor temperature and get notified when it crosses a certain threshold.\n\nOpen the context menu (`⋮`) on the panel to the left and select _More_ -> _New alert rule_ to get started\n"
   }
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_humidity{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_precip_mm{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)* 0.03937007874",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "avg(weather_forecast_uv_index{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Condition and Astro Timings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{namespace=\"weather-service\"} |= \"Forecast Condition\" | logfmt | location=~\"$location\" | forecast_day=\"$forecast_day\""
    }
   ]
  }
 ]
}