{
 "title": "Usage Insights - 5 - Metrics Ingestion",
 "description": "This is a Usage Insights dashboard that shows stats about metrics ingestion and discard rates for metric samples, exemplars and metadata.",
 "tags": [ "grafanacloud" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Hosted Metrics Instance",
    "query": {
     "query": "label_values(grafanacloud_instance_info{type=~\"prometheus|graphite.*\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hosted Metrics Instances",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n    max by (id, name, type) (grafanacloud_instance_info)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (id, name, type) (grafanacloud_instance_info)\n* on (id) group_left ()\n(\n    sum by (id) (\n        sum_over_time(grafanacloud_instance_samples_per_second[$__range:1m])\n    )\n    / ($__range_s / 60)\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (id, name, type) (grafanacloud_instance_info)\n* on (id) group_left ()\n(\n    sum by (id) (\n        sum_over_time(grafanacloud_instance_samples_discarded_per_second[$__range:1m])\n    )\n    / ($__range_s / 60)\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (id) (grafanacloud_instance_info)\n* on (id) group_left ()\n(\n    sum by (id) (\n        sum_over_time(grafanacloud_instance_exemplars_discarded_per_second[$__range:1m])\n    )\n    / ($__range_s / 60)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (id) (grafanacloud_instance_info)\n* on (id) group_left ()\n(\n    sum by (id) (\n        sum_over_time(grafanacloud_instance_metadata_discarded_per_second[$__range:1m])\n    )\n    / ($__range_s / 60)\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (id, name, type) (grafanacloud_instance_info)\n* on (id) group_left ()\n(\n    sum by (id) (\n        sum_over_time(grafanacloud_instance_exemplars_per_second[$__range:1m])\n    )\n    / ($__range_s / 60)\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (id, name, type) (grafanacloud_instance_info)\n* on (id) group_left ()\n(\n    sum by (id) (\n        sum_over_time(grafanacloud_instance_metadata_per_second[$__range:1m])\n    )\n    / ($__range_s / 60)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosted Metrics Instances",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "This panel shows list of Hosted Metrics instances, together with average rate of ingested and discarded samples, exemplars and metadata.\n\nAverage is computed over entire selected time range.\n\nClicking on instance will select the instance in following panels."
   }
  },
  {
   "title": "Ingested Samples, Exemplars, Metadata / second (Instance: $instance)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (id) (grafanacloud_instance_samples_per_second{id=~\"$instance\"})\n* on (id) group_left(name)\nmax by (id, name) (grafanacloud_instance_info{id=~\"$instance\"})\n> 0\n",
     "legendFormat": "{{name}} - samples"
    },
    {
     "expr": "sum by (id) (grafanacloud_instance_exemplars_per_second{id=~\"$instance\"})\n* on (id) group_left(name)\nmax by (id, name) (grafanacloud_instance_info{id=~\"$instance\"})\n> 0\n",
     "legendFormat": "{{name}} - exemplars"
    },
    {
     "expr": "sum by (id) (grafanacloud_instance_metadata_per_second{id=~\"$instance\"})\n* on (id) group_left(name)\nmax by (id, name) (grafanacloud_instance_info{id=~\"$instance\"})\n> 0\n",
     "legendFormat": "{{name}} - metadata"
    }
   ]
  },
  {
   "title": "Ingestion Rate",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 7 },
   "options": {
    "content": "This panel shows rate of received samples, exemplars and metadata.\n\nDeduplicated and discarded samples, exemplars and metadata are not counted."
   }
  },
  {
   "title": "Discarded Samples / second (Instance: $instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (id, reason) (grafanacloud_instance_samples_discarded_per_second{id=~\"$instance\"})\n* on (id) group_left(name)\nmax by (id, name) (grafanacloud_instance_info{id=~\"$instance\"})\n> 0\n\n",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Discarded Exemplars / second (Instance: $instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum by (id, reason) (grafanacloud_instance_exemplars_discarded_per_second{id=~\"$instance\"})\n* on (id) group_left(name)\nmax by (id, name) (grafanacloud_instance_info{id=~\"$instance\"})\n> 0",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Discarded Metadata / second (Instance: $instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 13, "y": 17 },
   "targets": [
    {
     "expr": "sum by (id, reason) (grafanacloud_instance_metadata_discarded_per_second{id=~\"$instance\"})\n* on (id) group_left(name)\nmax by (id, name) (grafanacloud_instance_info{id=~\"$instance\"})\n> 0",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Discard Rate",
   "type": "text",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 17 },
   "options": {
    "content": "These panels shows rate of discarded samples, exemplars and metadata, together with discard reason."
   }
  },
  {
   "title": "Ingestion Error Details (Instance: $instance)",
   "type": "logs",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{instance_type=\"metrics\", instance_id=~\"$instance\"} |~ \"error while ingesting|failed to process sample due to error|failed to process exemplar due to error|failed to push aggregation result|the sample has been rejected\" | logfmt | line_format \"{{.err}}\""
    }
   ]
  },
  {
   "title": "Log Messages for Discarded values",
   "type": "text",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 28 },
   "options": {
    "content": "This panel shows log messages from relevant Hosted Metrics components that discard samples, exemplars or metadata.\n\nFor description of errors, please consult [Grafana Mimir Errors catalog](https://grafana.com/docs/mimir/latest/manage/mimir-runbooks/#errors-catalog).\n\nTo change configuration values mentioned in the log messages, please contact Grafana support."
   }
  }
 ]
}